name: npm publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3

      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: pnpm i

      - name: Check type
        run: pnpm check:type

      - name: Check lint
        run: pnpm lint

      - name: Build
        run: pnpm build

      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
        run: pnpm publish  --access public --no-git-checks
